### ISSUE TITLE
Question about who no small object optimization?

### ISSUE THREAD

**Issue by Kered13** [jbcoe/value_types#102]
This is just a question, sorry that I do not know where else to ask this.

I was skimming over the `polymorphic_value` papers and noticed that in the [original paper](https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2019/p0201r5.html) small object allocation is encouraged, while in the [new paper](https://github.com/jbcoe/value_types/blob/main/DRAFT.md) it is expressly called out as not supported. I would just like to better understand the reason for the change? Was this due to something learned from the implementation, or perhaps a reconsideration of the tradeoffs involved?

The new paper does not provide much explanation, other than saying that a small object implementation would need to be a different type (true, but does not explain why that type was not chosen for the implementation).

**Comment by jbcoe** [comment]
Thanks for the question. This is the right place to ask and we’ll get back to you with a detailed response.

**Comment by jbcoe** [comment]
We're looking into SBO in https://github.com/jbcoe/value_types/tree/dev-jbcoe-remove-sbo-discussion

**Comment by jbcoe** [comment]
#107 updates the draft to discuss SBO, not prohibit it. 

We remove some constexpr from polymorphic to make an SBO implementation compliant and we add an (experimental) SBO implementation. 

The reference implementation is unchanged: it will always allocate but is the same size as a pointer.
