### ISSUE TITLE
Create C++11 implementations of indirect and polymorphic

### ISSUE THREAD

**Issue by jbcoe** [jbcoe/value_types#180]
@Ukilele would this be of interest to you?

**Comment by jbcoe** [comment]
@Twon is picking this up.

**Comment by Ukilele** [comment]
1. What is the motivation for C++11 implementations? Is the goal to make it more accessible for others to test it?
2. Do you strive for a single header for `polymorphic` (and `indirect` respectively) where certain features (like `operator<=>`) are ecapsulated in an `#ifdef feature-available` or do you want to have two different headers (`indirect.h` (for c++20) and `indirect_cpp11.h` (for C++11) )?

**Comment by jbcoe** [comment]
Ideally different headers just to keep things readable and isolated. We’ve done this for experimental implantations of polymorphic already.

We want to get these types into the hands of as many folk as possible. Not everyone has C++20. C++11 is probably as far back as we can go.

**Comment by jbcoe** [comment]
@Ukilele we’re on a  flight for the next 12+ hours if you’d like to start/try?

**Comment by Ukilele** [comment]
I wish you a save flight back! I hope you had a great time in Kona and I am definitely interested in hearing what the outcome of your presentation was.
If I find the time to start working on this issue next week, I will. But I can't make any guarantees.

**Comment by Ukilele** [comment]
I make good progress with the implementations of `polymorphic` and `indirect` for C++11. But I could need some help with all the "infrastructure" (CI, CMakeLists, test-environment, ...). I will upload my changes tomorrow and maybe someone of you could then contribute the infrastructure?

**Comment by jbcoe** [comment]
A fine idea! Happy to wire up your code.

**Comment by Twon** [comment]
Yes, also happy to assist here!  Once you push up your changes we can contribute to the branch to address this.

**Comment by Ukilele** [comment]
I created the branch https://github.com/jbcoe/value_types/tree/dev-ukilele-c++11. It contains the folder "c++11" with a header for [polymorphic ](https://github.com/Ukilele/value_types/blob/dev-ukilele-c%2B%2B11/c%2B%2B11/polymorphic_11.h) and one for [indirect](https://github.com/Ukilele/value_types/blob/dev-ukilele-c%2B%2B11/c%2B%2B11/indirect_11.h). That's all I've done so far.

An open TODO that I will work on in the near future:
1. In C++20 we have `[[no_unique_address]]` which we applied to our Allocators. In C++11 we would have to implement Empty Base Class Optimization ourselves, which I didn't do yet. Therefore the unit-test that check of `sizeof` will fail. I will implement this at some point.

The more important thing now is to tie up the CMake/Bazel project stuff. And to tie up the unit tests. Right now I would vote for one set of unit-tests, that we compile twice, once for C++11 and once for C++20 and include the files (indirect.h vs indirect_11.h) respectively. But all this is something which I am not experienced with and which I am sure you will resolve :)

**Comment by Ukilele** [comment]
One more thing: I don't know which compilers we are aiming to support. Different compilers seem to provide different support of C++11. On godbolt I tested gcc 7.1 and clang 3.9.0. All the C++11-compatible unit tests run (except the one testing for `sizeof` which I will make work soon). I did not test Visual Studio.

https://cpp11.compiler-explorer.com/z/c4PYoeW7z

**Comment by Twon** [comment]
Closing as now completed
