### ISSUE TITLE
Explore idea for incomplete type support

### ISSUE THREAD

**Issue by jbcoe** [jbcoe/value_types#199]
@lewissbaker suggested:

"Did you explore defining the default-constructor using something like:

```c++
template<typename U = T>
indirect() requires std::constructible_from<U>;
```
this would allow defering the computation of whether the T is default-constructible until it’s actually used/referenced.

e.g. https://godbolt.org/z/q6dEn3Wr9

You get into trouble if anyone actually asks that question while `T` is incomplete.
i.e. asks `std::constructible_from<indirect<T>>` while `T` is incomplete (it will report false, even if `T` later turns out to have a default-constructor once defined).
If you uncomment the static-assert in the godbolt example above then it makes the program ill-formed - not because the static_assert fails, but because it forces the compiler to compute the fact that the default constructor is not present, then later when you define the `T` and try to use indirect default constructor, there is none defined.

Attempts to odr-use the default constructor while the `T` is incomplete will always be a compile-error, however."

**Comment by jbcoe** [comment]
This works and needs extending to turn all static assertions into requirements.

**Comment by Twon** [comment]
Closing this as we are unable to apply this uniformly as this will not apply to copy constructors.
