### ISSUE TITLE
Determine whether these types can be register optimised as specified, unlike `unique_ptr`

### ISSUE THREAD

**Issue by philipcraig** [jbcoe/value_types#203]

**Comment by lewissbaker** [comment]
My impression is that it won't be register optimisable as it has a non-trivial destructor.

But, unlike `std::unique_ptr`, there is no way to "steal" the owned object from an `indirect` and pass it as a raw-pointer and reconstitute the `indirect` on the other side of a function-call boundary.

**Comment by jbcoe** [comment]
Is this because it has an allocator?
When the allocator is the default one, could we special case things?

**Comment by lewissbaker** [comment]
Consider the following:

```c++
__attribute__((noinline)) void callee(indirect<foo> x) {
  indirect<foo> x_local(std::move(x));
  // use x_local
}

void caller()  {
  indirect<foo> obj(42);
  callee(std::move(obj));
}
```
In this case the `caller()` constructs the prvalue for the function parameter `x`.
However, the lifetime of this prvalue exists until the end of the full expression on the caller's scope.
The caller cannot necessarily tell that the callee will unconditionally move/steal the contents of `x`, and so the caller needs to inspect the `x.p_` member in the destructor to work out whether it needs to destroy the owned object of the temporary.
The compiler should be able to deduce that the `obj` object's destructor is a no-op, however, just not that the `x` temporary has a no-op destructor.

This is independent of whether the object uses an allocator or not.

**Comment by jbcoe** [comment]
From discussion, these types cannot be register-optimised.
