### ISSUE TITLE
Add missing requires clauses

### ISSUE THREAD

**Issue by jbcoe** [jbcoe/value_types#21]
My minimal implementations don’t make any of the checks that they perhaps should. We’d get better compiler errors with the addition of concept checks. We need to be sure that incomplete types are still supported (like in indirect_value) though as that’s a useful use case (Pimpl).

Ideally we could check that the newly added requirements are doing the right thing in tests.

**Comment by jbcoe** [comment]
@Twon to review and close.

**Comment by Twon** [comment]
Closed as I following a review of all requires statements I believe these are required and inline with expectations
