### ISSUE TITLE
Constructor `Node(const indirect<Node>& parent)` can't be called

### ISSUE THREAD

**Issue by Ukilele** [jbcoe/value_types#214]
This issue is a consequence of https://github.com/jbcoe/value_types/pull/186 (which itself was a consequence of https://github.com/jbcoe/value_types/pull/128). I came up with a (possibly contrived) issue with the latest version of our [constructor](https://github.com/jbcoe/value_types/blob/main/indirect.h#L82):

```c++
#include <https://raw.githubusercontent.com/jbcoe/value_types/main/indirect.h>

struct Node {
    Node() = default; //ctor 1
    Node(xyz::indirect<Node>& parent) {} //ctor 2
};

void f() {
    xyz::indirect<Node> root;
    xyz::indirect<Node> child(root); //This will call the copy constructor of indirect and not the ctor 2 of Node
}
```

I know that in https://github.com/jbcoe/value_types/issues/159, I was complaining about the exactly opposite behavior that I am complaining about now. I am not sure what the desired behavior is. Should `xyz::indirect<Node> child(root);` call the copy-constructor of `indirect` or `ctor 2` of `Node`?

**Comment by jbcoe** [comment]
At first glance, the current behaviour is correct.

```
A a;
A aa(a); // I'd expect `A(const A&)` to be called
```

Please let me know if I've got this muddled.

**Comment by jbcoe** [comment]
Guessing that this is ok. @Ukilele please re-open if I'm mistaken.
