### ISSUE TITLE
Should the owned object of `indirect` always be initialised using _Uses-allocator construction_?

### ISSUE THREAD

**Issue by lewissbaker** [jbcoe/value_types#218]
For the default constructor the wording currently specifies that the owned object is initialized by calling the default constructor.

However, where the owned object is allocator-aware, perhaps the `indirect` default constructor and the `indirect(std::allocator_arg, alloc)` constructor should be calling the allocator-aware constructor of the owned object so that the allocator can be propagated to child objects as appropriate.

If so, perhaps these constructors should be speciifed to use _Uses-allocator construction_?

**Comment by Twon** [comment]
Yes, agree, allocators should propagate to the owned objects. So constructors should use Uses-allocator construction.  I can add this and tests.

**Comment by jbcoe** [comment]
Possibly relavant: https://rawgit.com/google/cxx-std-draft/allocator-paper/allocator_user_guide.html#alloc

**Comment by lewissbaker** [comment]
At the end of the day, the object needs to be initialized using the elements of the tuple returned from `std::uses_allocator_construction_args<T>(alloc, other_args...)`.

From looking at `scoped_allocator_adaptor`, it seems that it is the allocator's responsibility to implement `Alloc::construct()` in terms of a call to `std::uses_allocator_construction_args`. See https://eel.is/c++draft/mem#allocator.adaptor.members-9

Also, the _Allocator-aware containers_ requirements indicate that elements should be initialized with a call to `allocator_traits<A>::construct()`. See https://eel.is/c++draft/container.alloc.reqmts#2.1

So, my understanding is that calling `allocator_traits<Alloc>::construct` is the right thing to do here. In which case the implementation would seem to be doing the right thing and it's just the specification that needs to be updated.

You may want to double-check with an allocator expert, however.

**Comment by jbcoe** [comment]
I think this is the right call, we can double check with @NinaRanns

**Comment by jbcoe** [comment]
The same applies for polymorphic, whatever we decide is right.

**Comment by jbcoe** [comment]
For now this issue is closed by #271

**Comment by NinaRanns** [comment]
Just addressing some points in  this issue. Using construct is correct. The allocator responsibilities of the indirect are solely for the memory it manages. Whether the allocator is passed to the owning object is determined by the type of the allocator so talking about uses allocator construction of the owning object is wrong - if the allocator is not scoped, no such construction will happen (this is all managed by `allocator_traits<A>::construct`).  The changes mentioned in the other issue make the wording incorrect. We should probably be talking about the owning object being constructed with `allocator_traits<A>::construct`. We may also want to pull in some wording from https://eel.is/c++draft/container.alloc.reqmts depending on what allocator guarantees we want to have here

**Comment by Twon** [comment]
Some relevant info: 
- https://stackoverflow.com/questions/72311730/what-is-uses-allocator-and-scoped-allocator-construction-in-c
- https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2018/p0591r4.pdf
