### ISSUE TITLE
`indirect` default constructor needs to specify what kind of initialization is used

### ISSUE THREAD

**Issue by lewissbaker** [jbcoe/value_types#219]
The wording for the default constructor says that it:
> Constructs an indirect owning a default-constructed `T`.

Is the intent that this the object is _default-initialized_ or _value-initialized_?

e.g. say we write the following:
```c++
struct parent {
  struct data {
    int x;
    int y;
  };

  indirect<data> member;
};
```

Do you expect the implicit default-constructor to zero-initialize the x and y members, or leave them uninitialized?

**Comment by lewissbaker** [comment]
Related to #218

**Comment by jbcoe** [comment]
What existing precedent is in the standard library? We should not be innovating here.

**Comment by lewissbaker** [comment]
If, based on the outcome of #218, we say that objects are always 'uses-allocator constructed' then it's easy - we just do whatever `allocator_traits<A>::construct()` does.

Otherwise, for precedent, we have:
- `std::vector` does "default-inserted elements" when you initailize the vector with a size but no default value
  See https://eel.is/c++draft/vector.cons#4
  The definition of "default-inserted element" is that it calls `allocator_traits<Alloc>::construct(alloc, p)`
  See https://eel.is/c++draft//container.requirements#container.alloc.reqmts-2.2

**Comment by jbcoe** [comment]
Saying that objects are always 'uses-allocator constructed' seems like the right way to go. Would you be able to suggest updated wording or point us at the right things to say?
