### ISSUE TITLE
`indirect` default constructor wording should specify what it can throw

### ISSUE THREAD

**Issue by lewissbaker** [jbcoe/value_types#220]
The default constructor wording should include a _Throws_ section that indicates it can throw any exception thrown by a call to the `Alloc::allocate()` function or any exception thrown by a call to the initialization of the owned object.

**Comment by jbcoe** [comment]
@lewissbaker Do we need throws wording everywhere a constructor could be called or an allocator could fail?

**Comment by jbcoe** [comment]
We need wording for just the default constructor, same for polymorphic.
