### ISSUE TITLE
Do you want to allow user-defined specializations of `indirect` or `polymorphic`?

### ISSUE THREAD

**Issue by lewissbaker** [jbcoe/value_types#221]
There is a blanket wording in `[namespace.std]` that permits users to declare explicit or partial specialization of any standard library class template provided the declaration depends on at least one program-defined type and the specialization meets the requirements of the original template.

Is this something that you want to allow for the `indirect` and `polymorphic` class templates?
If not, we should add some wording that prohibits such specializations.

**Comment by jbcoe** [comment]
This seems a reasonable way to allow users to define comparisons and hash for polymorphic. What are the downsides?

**Comment by lewissbaker** [comment]
The only concern I can think of here would be if you want to later add support for implicit conversion from e.g. `polymorphic<derived>` to `polymorphic<base>`. In this case, one of the classes would presumably need to reach into the implementation of the other class to transfer ownership and this would break if one of them was specialized by the user in a way that was incompatible with the original implementation.

Any operation involving another specialization of the class template would be restricted to only using the public API of that other specialization.

**Comment by jbcoe** [comment]
Thanks, I'll have a ponder.

**Comment by jbcoe** [comment]
I think we prohibit specializations - we can relax this later; the reverse is not true.

**Comment by jbcoe** [comment]
I'll add wording and update the changes table.
