### ISSUE TITLE
Consider adding support for `initializer_list` constructors

### ISSUE THREAD

**Issue by lewissbaker** [jbcoe/value_types#222]
For example, do we want to support writing the following:
```
auto x = std::indirect<std::array<int, 3>>{42, 99, 101};
```

**Comment by jbcoe** [comment]
This feels non-core but probably something we'll eventually want. How would we have to construct an indirect array without this constructor?

**Comment by jbcoe** [comment]
That is moderately unpleasant. We should probably allow explicit intitialzer-list constructors where T has one.

**Comment by Ukilele** [comment]
Adding support for `initializer_list` constructors would at least increase the consistency with the other wrapper types from the STL ([any](https://en.cppreference.com/w/cpp/utility/any/any), [optional](https://en.cppreference.com/w/cpp/utility/optional/optional), [variant](https://en.cppreference.com/w/cpp/utility/variant/variant), [expected](https://en.cppreference.com/w/cpp/utility/expected/expected)) 👍

**Comment by jbcoe** [comment]
@Ukilele would you be interested in adding implementation and wording (for indirect)?

**Comment by Ukilele** [comment]
@lewissbaker : `std::array<T, N>` isn't constructible from a `std::initializer_list<T>`. So even after adding the constructors, your original code sample (`std::indirect<std::array<int, 3>>{42, 99, 101};`) won't compile. And unfortunately there is no solution to make it compile as the initialization of std::array (e.g. `std::array<int, 3> arr = {1, 2, 3}`) uses [aggregate-initialization](https://en.cppreference.com/w/cpp/language/aggregate_initialization) which wrapper types (like std::indirect and std::optional) can't provide as they aren't aggregates.

@jbcoe I will raise a PR this evening.

**Comment by jbcoe** [comment]
Without a clear motivating example, I'm not sure we should do this. We can add constructors later.

`indirect<vector>` seems unlikely to be useful 😄

**Comment by jbcoe** [comment]
I don't think we should do this for P3019R3
