### ISSUE TITLE
`indirect` comparison operators should be conditionally noexcept

### ISSUE THREAD

**Issue by lewissbaker** [jbcoe/value_types#226]
The `indirect` class defines a number of comparison operators but declares them all to be `noexcept(false)`.

Ideally these functions would be conditionally noexcept based on whether the underlying operations that they dispatch to are noexcept.

i.e.
```
template<typename U, typename AA>
friend constexpr auto operator==(const indirect<T, Allocator>& lhs, const indirect<U, AA>& rhs)
  noexcept(noexcept(*lhs == *rhs));
```
or something equivalent to that.

**Comment by jbcoe** [comment]
This is right, we should update the draft and implementation.

**Comment by Twon** [comment]
Addressed in:
https://github.com/jbcoe/value_types/pull/250
https://github.com/jbcoe/value_types/pull/253
