### ISSUE TITLE
`indirect` copy/move-assignment operators need wording to say that if `this == &other` then has-no effect

### ISSUE THREAD

**Issue by lewissbaker** [jbcoe/value_types#232]
With the current wording self-copy-assignment or self-move-assignment would be undefined-behaviour as the wording specifies that the owned object is destroyed and then we initialize a new object from `other`'s owned object (which would now be destroyed in the case of self-assignment).

Consider adding the following phrase to the beginning of the assignment operator _Effects_ clause.

> If `this == addressof(other)` is `true`, then has no effects, otherwise...

**Comment by lewissbaker** [comment]
Note this was also considered for move-assignment in #192 , which rejected adding this check.

**Comment by jbcoe** [comment]
We now have

If `&other == this`, then has no effects.

In the draft for copy assignment and move assignment for both indirect and polymorphic.
