### ISSUE TITLE
`indirect()` move constructor should not move its allocator

### ISSUE THREAD

**Issue by lewissbaker** [jbcoe/value_types#233]
If the allocator is moved-from in the move constructor then this would leave both the rhs object in a valueless state _and_ with a moved-from allocator object.

Attempting to subsequently assign a new value to the `other` object using the copy-constructor where `allocator_traits<allocator_type>::propagate_on_copy_assignment::value` is `false`, or using the move-constructor where `allocator_traits<allocator_type>::propagate_on_move_assignment::value` is `false` would cause the assignment operator to try to use the allocator from the object being assigned to, which would be in a moved-from state.

I think that instead, you'd want to have the move-constructor (and move-assignment operator) copy the allocator instead of moving it if either of those two allocator_traits properties is `false`.

**Comment by jbcoe** [comment]
We're not moving from `alloc_` anywhere now in either implementation.
