### ISSUE TITLE
Indirect's move constructor should be conditionally noexcept (because of allocators)

### ISSUE THREAD

**Issue by jbcoe** [jbcoe/value_types#234]
see https://github.com/jbcoe/value_types/pull/223

**Comment by lewissbaker** [comment]
Note that it is not the move-constructor that needs to be conditionally noexcept, but rather the `indirect(std::allocator_arg_t, const Allocator& alloc, indirect&& other)` constructor.

I believe the `indirect(indirect&& other)` constructor should be able to be unconditionally noexcept.
