### ISSUE TITLE
`indirect` could avoid virtual destructor calls if it wrapped the owned object in a struct

### ISSUE THREAD

**Issue by lewissbaker** [jbcoe/value_types#239]
If the type of object owned by an `indirect<T>` object happens to be a type with a virtual destructor, the destructor of the `indirect<T>` object currently calls `obj->~T();` (via `allocator_traits::destroy()`), which will dispatch to the destructor's vtable entry.

If instead you allocated the object inside a struct with a member of type `T`, then when destroying the wrapper object the compiler would statically know that the concrete object type is `T` and so would be able to make a direct call to `T`'s destructor. This could lead to better inlining of code in the destructor.

e.g. something roughly along the lines of:
```
template<class T, class Alloc = std::allocator<T>>
class indirect {
  struct wrapper {
    template<typename... Args>
    requires std::constructible_from<T, Args...>
    wrapper(Args&&... args) noexcept(std::is_nothrow_constructible_from_v<T, Args...>) : owned(std::forward<Args>(args)...) {}
    
    [[no_unique_address]] T owned;
  };
  using wrapper_allocator = std::allocator_traits<Alloc>::template rebind_alloc<wrapper>;
  using wrapper_traits = std::allocator_traits<wrapper_allocator>;
  
  wrapper_traits::pointer p_;
  [[no_unique_address]] wrapper_allocator alloc_;
public:
  // etc...
};
```

Note this relates to the implementation rather than the wording - I believe the wording already allows this via phrasing in the front-matter indicating that it will use a rebound allocator that is either rebound to `T` or to some internal type.

**Comment by jbcoe** [comment]
This is super-cool. Thanks Lewis. Any takers? @Ukilele @Twon

**Comment by jbcoe** [comment]
This is a pure QoI improvement (although a nice one). Let's pick this up after we've got the next draft in shape.

**Comment by jbcoe** [comment]
I'm going to leave this for later QoI. I want to keep our reference implementation as simple as possible.
