### ISSUE TITLE
polymorphic<T> is not unconditionally copy-constructible

### ISSUE THREAD

**Issue by dvirtz** [jbcoe/value_types#267]
The paper states that while `indirect<T, Alloc>` is copy constructible where `T` is, `polymorphic<T, Alloc>` is unconditionally copy constructible but trying to instantiate `polymorphic<T>` where `T` is not copy constructible fails to compile:
```
struct NonCopyable {
    NonCopyable() = default;
    NonCopyable(const NonCopyable&) = delete;
    NonCopyable& operator=(const NonCopyable&) = delete;
    NonCopyable(NonCopyable&&) = default;
    NonCopyable& operator=(NonCopyable&&) = default;
};

using Pol = xyz::polymorphic<NonCopyable>;    
static_assert(std::copyable<Pol>);

int main() {
    Pol{};
}
```
```
/app/raw.githubusercontent.com/jbcoe/value_types/main/polymorphic.h:64:48: error: use of deleted function 'NonCopyable::NonCopyable(const NonCopyable&)'
   64 |   constexpr direct_control_block(Ts&&... ts) : u_(std::forward<Ts>(ts)...) {
      |                                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~
<source>:6:5: note: declared here
    6 |     NonCopyable(const NonCopyable&) = delete;
      |     ^~~~~~~~~~~
```
https://godbolt.org/z/44P4YnxsG

**Comment by jbcoe** [comment]
This is expected behaviour, how should we amend wording to make this clear?

**Comment by dvirtz** [comment]
I think it would be more clear if the wording said that `T` is required to be copy constructible.

**Comment by jbcoe** [comment]
Current wording (DRAFT.md) has 

```
explicit constexpr polymorphic();
```

...

```
explicit constexpr polymorphic(allocator_arg_t, const Allocator& alloc);
```

1. _Mandates_: `is_default_constructible_v<T>` is `true`, `is_copy_constructible_v<T>` is `true`.

Is there anything else we should amend?

Note that this constraint is on the constructor, not on `T`. `T` could be an abstract base class so need not be constructible or copy constructible.

**Comment by dvirtz** [comment]
Apologies, I was referring by wording to the textual description not the standardese. This requirement should be stated on the copy constructor as well I assume.
Also, it's possible to have a non-copyable type be default constructible by conditionally excluding the `clone` function: https://godbolt.org/z/43sEcqdT4
Any reason to disallow it?

**Comment by jbcoe** [comment]
I think we need another type (unique_polymorphic) to disable copying. It's possible that the base type is non-copyable but the derived types are (intended, common use). Since the derived types are type erased, we can only check that they are copyable in constructors and can't make the copy-constructor conditional. One option would be to make polymorphic throw if the derived type is not copyable - I don't much care for this.
