### ISSUE TITLE
HTML rendered DRAFT.md mangles smart quotes

### ISSUE THREAD

**Issue by ben-craig** [jbcoe/value_types#291]
The github rendered DRAFT.md has this line:
`Replace use of "erroneous" with "undefined behaviour".`
The revision on from https://isocpp.org/files/papers/P3019R3.html:
`Replace use of â€œerroneousâ€ with â€œundefined behaviourâ€.`

You need something like the following in your .html:
`<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">`
I'm not sure how to get it there though, or I'd suggest it myself.

**Comment by Twon** [comment]
Thanks for raising this @ben-craig.  Adding that to the MD appears to fix the generated HTML.
