### ISSUE TITLE
Please don't use trailing underscores for private data members

### ISSUE THREAD

**Issue by jwakely** [jbcoe/value_types#311]
https://github.com/jbcoe/value_types/blob/17eb8a941ceee73a6ea804edbc74bacca99b9738/DRAFT.md?plain=1#L539-L540

I suggest just _`p`_ and _`alloc`_ not `p_` and `allocator_`.

Also the type `pointer` is used before it's declared. If you move the private members to the end that would not be an issue.

**Comment by Twon** [comment]
Thanks for raising this @jwakely.  I'll address this before R4 of the paper.
