### ISSUE TITLE
Default constructor should use Constraints not Mandates

### ISSUE THREAD

**Issue by jwakely** [jbcoe/value_types#313]
https://github.com/jbcoe/value_types/blob/17eb8a941ceee73a6ea804edbc74bacca99b9738/DRAFT.md?plain=1#L693

The default constructor should be constrained away if the contained value is not default constructible. Otherwise `is_default_constructible_v<indirect<X>>` will always be true, but default constructing an `indirect<X>` might be a hard error.

Make it SFINAE friendly, use _Constraints_.

**Comment by jbcoe** [comment]
We found that _Constraints_ (ie `requires`?) broke support for having an `indirect<T>` member when `T` was an incomplete type (which we need). Is there a better approach?

**Comment by jbcoe** [comment]
@jwakely how can we use _Constraints_ for an incomplete type?

**Comment by jwakely** [comment]
Sorry, I missed the emails last month.

The type has to be complete when you actually default-construct it, so what breaks? 

I assume the problem is that checking `is_default_constructible_v<indirect<X>>` is not allowed until `X` is complete? Maybe that's acceptable? It's the same as `is_default_constructible_v<X>`. You can't check that for an incomplete type.

Using constraints would mean that at least it gives the right answer when `X` _is_ complete (which again, is the same as `is_default_constructible_v<X>`).

But I guess you want `indirect<X>` to be complete unconditionally, and so we can't just say it's complete when `X` is complete, and let that dictate when you're allowed to check its constructibility.

It seems that making it a mandates gives you the ability to use `is_default_constructible_v<indirect<Incomplete>>` ... but it gives the wrong answer. Is that useful? Is there something else it permits that I'm missing?

**Comment by jwakely** [comment]
> Having `is_default_constructible_v<indirect<Incomplete>>` return the wrong answer is not useful. Can we do better and support incomplete types?

I don't _think_ so. I think the only way to do that would be to default construct to the empty (i.e. moved-from) invalid state, which obviously isn't the intended API.

I think you have to choose between:

- always allow `is_default_constructible_v` to be checked, but the value is wrong sometimes.
- you can only check if sometimes, but when you can check it, it's reliable (unless the underlying type lies when that trait is checked for it, which you can't do anything about).


> I've mentally mapped _Constraints_ onto `requirements` is that right?

Yes, _Constraints_: removes a function from the overload set if the constraints fail. A conforming way to implement that (and the most straighforward) is to just use a `requires` clause to enforce the _Constraints_:

_Constraints_ == `requires`
_Mandates_ == `static_assert` (or just any less user-friendly compiler error)
_Requires_ == precondition, get this right or else UB! (Maybe enforced by a runtime `assert` or similar if the impl is willing and able to check it).

**Comment by jwakely** [comment]
IMHO no, it's not. We have similar traits that lie because they can't tell the right answer, e.g. `is_copy_constructible_v<vector<unique_ptr<T>>>`

**Comment by jbcoe** [comment]
Could `is_copy_constructible_v<vector<unique_ptr<T>>>` be amended (by modifying vector) to not lie? We don't want to be in a place that puts value-types beyond the scope of future improvements.

**Comment by jwakely** [comment]
For `vector<unique_ptr<T>>` maybe, but for `vector<unique_ptr<T>, Alloc>`, no, and for `vector<UserType, A>` no.

**Comment by jbcoe** [comment]
Why can't `is_copy_constructible_v<vector< >>` be fixed for `UserType`? This feels fundamental.

I'd naively think that once can add an `is_copy_constructible_v<T>` _Constraint_ to `vector<T>`

**Comment by jwakely** [comment]
because vector uses the allocator to construct its elements and `allocator_traits<A>::allocate` is not constrained

**Comment by jwakely** [comment]
`is_copy_constructible` is **not** the right condition. That's not how the elements are constructed.

**Comment by jwakely** [comment]
So you could add it, but it would be wrong.
