### ISSUE TITLE
P3019R4 says that polymorphic's moved-from state is valueless, which is not the author's intent

### ISSUE THREAD

**Issue by mhoemmen** [jbcoe/value_types#358]
Per today's (2024/02/06) wording review, the author's intent for `polymorphic` is to make a small buffer optimization (SBO) legal.  As a result, they cannot require that the moved-from state be valueless.  Nevertheless, [R4 of the paper](https://isocpp.org/files/papers/P3019R4.html) says: "Postconditions: other is valueless."

**Comment by jbcoe** [comment]
The wording

Postconditions: `other` is valueless.

occurs only in wording for `indirect` which is not intended to support a small buffer optimisation. `polymorphic` can support a small buffer optimisation, I think the current wording supports that.

Thanks for raising this, but I think we're good.
