### ISSUE TITLE
Redundant condition in polymorphic's constraints

### ISSUE THREAD

**Issue by jwakely** [jbcoe/value_types#403]
https://github.com/jbcoe/value_types/blob/e9eef50df45197051e2dd5f84ca368fe5d65b419/DRAFT_COROLLARY.md?plain=1#L263-L266

The `is_same_v<remove_cvref_t<U>, polymorphic>` is `false` constraint is redundant. The first condition checks that `U` is derived from `T`, so it can't be `polymorphic<T>` then.

Simiarly for the next constructor.

You could choose to keep it for consistency with the equivalent `indirect` constructor, or remove it as redundant.

**Comment by jbcoe** [comment]
I think we need to keep it. `is_base_of_v<T, T>` is (surprisingly to me) true. https://godbolt.org/z/sGvefd9bh

**Comment by jwakely** [comment]
Oh of course
