### ISSUE TITLE
polymorphic_inline_vtable.h doesn't support moving with non-equal allocator

### ISSUE THREAD

**Issue by jwakely** [jbcoe/value_types#410]
https://github.com/jbcoe/value_types/blob/a7fa0db8f4710853f9c4469c6749102a3906e7b1/experimental/polymorphic_inline_vtable.h#L202-L207

This assumes it's OK to transfer ownership from the rvalue `other`, but if `other.alloc_ != this->alloc_` then that doesn't work.

You need to clone a new control block for the non-equal allocator case, but the clone function only supports copy not move.

**Comment by jbcoe** [comment]
I'll drop inline-vtable. Thanks for playing with our experiments.
