### ISSUE TITLE
Convertibility between `indirect<T : U>` and `polymorphic<U>`

### ISSUE THREAD

**Issue by MFHava** [jbcoe/value_types#441]
Something that came up recently in our codebase using `indirect` and `polymorphic` was the need to move a contained object from an `indirect` to a `polymorphic`.

[Usage example](https://godbolt.org/z/G7ohY71E4)

**Comment by jbcoe** [comment]
In brief I think you'd like this to work:

```
indirect<Circle, MyAlloc<Circle>> ind(/* some args */);
polymorphic<Shape, MyAlloc<Shape>> pol(std::move(ind));
```

This feels reasonable but not feasible with the current control-block implementation of polymorphic. 

If we add another form of control block then I'm pretty confident that it can be made to work. polymorphic will still need to allocate though to create the control block (which will own the object formerly in `ind`). Is that tolerable?

Do I understand the problem correctly?

**Comment by MFHava** [comment]
I had to check the implementation to get what you mean with „control-block“ - yes I agree, in this design you would need an additional allocation for the „control-block“. Yes, IMHO this operation would still be beneficial even if we can‘t guarantee noexcept-ness of it.

Note: From my reading of P3019R10, that is not the only valid implementation strategy (e.g. an external, manually constructed vtable design would enable these moves without additional dynamic memory allocations). If we propose this functionality in a timely manner, we might be able to convince implementers to design their `polymorphic` in a way that does not require additional allocations…

**Comment by MFHava** [comment]
We would have to drop support for `constexpr` from `polymorphic` (aligning it with the polymorphic function wrappers) to enable designs without additional overloads.

**Comment by jbcoe** [comment]
I'd like to keep constexpr without compelling cause to do otherwise.

Is your use case a common problem?

**Comment by MFHava** [comment]
On further deliberation, I don't think supporting this is worth the hassle ...

What may be of value is going from `polymorphic<T : U>` to `polymorphic<U>` but as P3019 correctly points out, that could happen as a pure extension...

**Comment by jbcoe** [comment]
Thanks Michael. I’ll close this for now.

please re-open if priorities change.
