### ISSUE TITLE
What does `has_value()` of a moved from `std::optional<indirect>` return?

### ISSUE THREAD

**Issue by jiixyj** [jbcoe/value_types#480]
The move constructor and move assignment operator of `std::optional` have a [postcondition](<https://eel.is/c++draft/optional#ctor-34>): `rhs.has_value()` must still be true when `rhs` was engaged before the operation.

I'm wondering how to implement this with an optimized `std::optional<indirect>` that has the same size as `indirect`. A straightforward implementation would return `rhs.has_value() == false` (as the moved from indirect is in the should-not-be-observed empty state) but that would violate the postconditions of `optional(optional<U>&& rhs)`.

Should those postconditions of `std::optional` be weakened?

**Comment by jiixyj** [comment]
I guess the question really is: what is the _value_ of a `std::optional<indirect>`? As far as I can see, `std::optional` really wants it to be like this:

```txt

std::optional<indirect<T>>:

+--------------+--------------+-------------+-------------+------------- ... -+------------+
|              | valueless    |             |             |                   |            |
| std::nullopt |   after      | T value 1   | T value 2   | T value ...       | T value n  |
|              |    move      |             |             |                   |            |
+--------------+--------------+-------------+-------------+------------- ... -+------------+

 \------v-----/ \------------------------------------v------------------------------------/
  !has_value()                                  has_value()
```

This is problematic, because the "valueless after move" state shouldn't be considered part of the value of an `indirect<T>`.

In an optimal implementation, one would like to be able to represent the `std::nullopt` value and the "valueless after move" state with the same bit pattern (a null pointer).

Of course, one could play tricks by using the unused pointer bits for the `std::nullopt` state. A `nullptr` could represent the "valueless after move" state, and a null pointer with its last bit set to "1" could mean the `std::nullopt` state.

I wonder if this complication is really worth it, though. It would really be best if the _value_ of a `std::optional<indirect<T>>` can be just the value of T plus a `std::nullopt` state.

**Comment by jbcoe** [comment]
As it stands, a moved-from engaged `optional<T>` has a `T` in a moved-from state. It is still engaged.

This means, as you say, that `where `oi` is an `optional<indirect<T>>`, after being moved from `oi.has_value()` as `true` and `oi->valueless_after_move()` is `true`. The optional has a value (an indirect) but the indirect is valueless after move.
This seems unlikely to be semantically useful.

In an earlier revision of P3019 we looked at specialising optional for indirect and polymorphic but were discouraged from pursuing this design direction as it's not core to indirect or polymorphic. Implementers in the room appeared to suggest that they would take the opportunity to apply the (size-based) optimisation you suggest. If this feels worth further clarifying I'd encourage you to draft a paper for C++26.

**Comment by jiixyj** [comment]
Thank you for your thoughts on this! I'll try to write something up.

**Comment by jbcoe** [comment]
I’ll close this as there is no work needed or planned as part of this repository.

please get in touch if you need review, contacts or input.
