### ISSUE TITLE
Make `swap` ADL-proof

### ISSUE THREAD

**Issue by Ukilele** [jbcoe/value_types#57]
In the implementation of `indirect` and `polymporphic` `swap` gets called 8 times. Sometimes the member functions `indirect::swap` and `polymorphic::swap` (e.g. `swap(tmp);`) get called. And sometimes `std::swap` (https://eel.is/c++draft/utility.swap#lib:swap) on two pointers (e.g. `swap(p_, other.p_)` with `using std::swap` in the line above) gets called. The point is that `swap` gets called unqualified, i.e. it is subject to ADL. But we already know which overloads of `swap` we want to call and don't need/want different overloads to be picked by ADL. While there is no advantage in calling `swap` unqualified, there might be a disadvantage in doing so: I came up with an example, even though it is very contrived:
```cpp
template<class T>
struct Holder { T value; };

class Incomplete;

template<class T>
struct X {};

using Indirect = xyz::indirect<X<Holder<Incomplete>>>;

void TestSwap(Indirect& a, Indirect& b)
{
    a.swap(b);
}
```
The snippet does not compile, as `a.swap(b)` makes an unqualified call to `swap` [here](https://github.com/jbcoe/value_types/blob/main/indirect.h#L184). The arguments  (`p_` and `other.p_`) are of type `X<Holder<Incomplete>>*`. To perform ADL, the compiler has to instantiate several types, including `Holder<Incomplete>`. If you want to protect against this issue, I suggest to fully qualify all calls to `swap`.

If you want to have a more in depth discussion of the topic, I can recommend [ADL can interfere even with uglified names](https://quuxplusone.github.io/blog/2019/09/26/uglification-doesnt-stop-adl/) and [What is the std::swap two-step?](https://quuxplusone.github.io/blog/2020/07/11/the-std-swap-two-step/).

**Comment by jbcoe** [comment]
Thanks for this. If you have a proposed fix we’d be happy to merge it!

thanks for your continued interest in our work on value types.

**Comment by jbcoe** [comment]
@Ukilele Can you take a look at #61? I think this does the necessary.

I suspect that swap needs revisiting once the allocators work is done but this PR should improve things none the less.
