### ISSUE TITLE
Review and update noexcept status

### ISSUE THREAD

**Issue by jbcoe** [jbcoe/value_types#78]
The standard makes some functions conditionally noexcept, we should do the same.

**Comment by Twon** [comment]
Example of conditionally noexcept method for `sdt::unique_ptr`: https://eel.is/c++draft/unique.ptr.single.observers

**Comment by Twon** [comment]
PR https://github.com/jbcoe/value_types/pull/59 now contains 3 conditional noexcept methods for each of `indirect` and `polymorphic`. This lines up with the few usages of conditional noexcept already in the standard. For instance, as pointed out by Thomas Russel, `std::vector::swap` has conditional noexcept specifications: https://eel.is/c++draft/vector#capacity

**Comment by jbcoe** [comment]
What do we need to do?

**Comment by Twon** [comment]
Nothing else, I was just waiting for a review of https://github.com/jbcoe/value_types/pull/59 before closing
