### ISSUE TITLE
Formatting of non-const-formattable types

### ISSUE THREAD

**Issue by Ukilele** [jbcoe/value_types#96]
Hi, this might be a contrived issue.
[DRAFT.md#xy13-formatter-support-indirectfmt](https://github.com/jbcoe/value_types/blob/main/DRAFT.md#xy13-formatter-support-indirectfmt) mentions the specialization of `std::formatter<indirect<T, Alloc>, charT>` when the underlying `T` supports specialisation of `std::formatter<T, charT>`. The `format`-function has the following signature (note that it takes the `indirect` by **const**`&`):
```c++
template<class FormatContext>
  typename FormatContext::iterator format(
    indirect<T, Alloc> const& value, FormatContext& ctx) const;
```
But there are some types `T`, where you can `std::format` a `T&`, but not a `const T&`. An example for such a type is `std::ranges::filter_view<V, P>`. In the following (contrived) example you can see how I can format a *filter_view*, but not an *indirect<filter_view>*:
```c++
#include <https://raw.githubusercontent.com/jbcoe/value_types/main/indirect.h>
#include <https://raw.githubusercontent.com/jbcoe/value_types/main/polymorphic.h>
#include <vector>
#include <ranges>
#include <print>

struct AllIn {
    bool operator()(int i) const { return true; }
};

int main() {
    std::vector v{1, 2, 3};
    auto filter = std::views::filter(v, AllIn{});
    std::println("filter = {}", filter);

    using FilterView = decltype(filter);
    xyz::indirect<FilterView> indirect(std::in_place, std::views::all(v), AllIn{});
    std::println("*indirect = {}", *indirect);
    std::println("indirect = {}", indirect); // error
}
```
So far I think this is a very contrived example and issue. But I at least wanted to make aware of it. In the future it might be worth it to extend formatting of `indirect<T, A>` to also work with *non-const-formattable* types.

**Comment by jbcoe** [comment]
We need to look at other standard library types and do the same thing. No need to innovate here.

**Comment by Twon** [comment]
Perhaps I'm missing something but I can't get this example working for the use case.  Currently, only the latest Visual Studio has support for the `<print>` header, any ideas what I am missing to reproduce this: https://godbolt.org/z/ahWacdanP

**Comment by Ukilele** [comment]
Here is the original sample: https://godbolt.org/z/zh9czreoK

Here is a "simplified" version which does not involve ranges, but my own custom type that is only formattable in a non-const verison (`MyNonConstFormattableType`) https://godbolt.org/z/sqoE5Txfj

It seems that both only work with clang 17.0.1 and options: -std=c++23 -stdlib=libc++

**Comment by Ukilele** [comment]
Regarding a solution: I just checked https://eel.is/c++draft/format.tuple#lib:format,formatter . This is the `std::formatter` for `std::pair` and `std::tuple`. The approach seems to be: If `const T` is formattable, then `format` takes a `const std::tuple<T>&` as parameter, otherwise it takes a `std::tuple<T>&` as parameter. Something similar was done at https://eel.is/c++draft/format.range, too.

**Comment by Ukilele** [comment]
I just learned, that libc++ does not define the macro `__cpp_lib_format` yet. This gets used in https://github.com/jbcoe/value_types/blob/main/indirect.h#L348 . So therefore under libc++ (which all my godbolt-samples used), the code will never work, because the #ifdef (`#if (__cpp_lib_format >= 201907L)`) in `indirect.h` will always be false.

**Comment by jbcoe** [comment]
Feel free to add your experiment in a PR and piggy-back off our test setup. We run on MSVC, Clang and GCC.

**Comment by jbcoe** [comment]
We've stripped out format support altogether so this is no longer an issue.
